import type { Metadata } from "next";
import { Jost, Oxanium } from "next/font/google";
import "./globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DanailGirl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` bg-white  dark:bg-white ${jost.variable} ${oxanium.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
